### ISSUE TITLE
pip install doesn't work

### ISSUE THREAD

**Issue by rshirodkar** [nelsond/prologix-gpib-ethernet#2]
Hi Nelson, 
I was trying to install your project using pip, by typing  pip install git+git://github.com/nelsond/prologix-gpib-ethernet.git
It gave me the following error
  
  Make sure you're either building from a fully intact git repository or PyPI
tarballs. Most other sources (such as GitHub's tarballs, a git checkout without
the .git folder) don't contain the necessary metadata and will not work.

    For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\RSHIRO~1
\AppData\Local\Temp\pip-3rczq6uu-build\

Can you please , help me with it. 

thank you , 
rohan

**Comment by nelsond** [comment]
What is your operating system (Windows?, which version?) and what is your Python version?

**Comment by rshirodkar** [comment]
Hi Nelson, My OS is windows 7 professional, python version 3.6.

**Comment by nelsond** [comment]
Thanks for your reply. I'll try to reproduce the error and hopefully find a fix.

**Comment by XavierTolza** [comment]
Exactly the same problem here. Windows 10, python 2.7 with anaconda
```
(C:\Users\<my name>\Miniconda2\envs\GPIBdriver) C:\Users\<my name>\Miniconda2\envs\GPIBdriver>python "C:\Users\<my name>\Downloads\prologix-gpib-ethernet-master\setup.py" install
Traceback (most recent call last):
  File "C:\Users\<my name>\Downloads\prologix-gpib-ethernet-master\setup.py", line 45, in <module>
    install_requires=[],
  File "C:\Users\<my name>\Miniconda2\envs\GPIBdriver\lib\distutils\core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "C:\Users\<my name>\Miniconda2\envs\GPIBdriver\lib\site-packages\setuptools\dist.py", line 338, in __init__
    _Distribution.__init__(self, attrs)
  File "C:\Users\<my name>\Miniconda2\envs\GPIBdriver\lib\distutils\dist.py", line 287, in __init__
    self.finalize_options()
  File "C:\Users\<my name>\Miniconda2\envs\GPIBdriver\lib\site-packages\setuptools\dist.py", line 471, in finalize_options
    ep.load()(self, ep.name, value)
  File "c:\users\<my name>\miniconda2\envs\gpibdriver\.eggs\setuptools_scm-1.15.6-py2.7.egg\setuptools_scm\integration.py", line 22, in version_keyword
  File "c:\users\<my name>\miniconda2\envs\gpibdriver\.eggs\setuptools_scm-1.15.6-py2.7.egg\setuptools_scm\__init__.py", line 119, in get_version
  File "c:\users\<my name>\miniconda2\envs\gpibdriver\.eggs\setuptools_scm-1.15.6-py2.7.egg\setuptools_scm\__init__.py", line 97, in _do_parse
LookupError: setuptools-scm was unable to detect version for 'C:\\Users\\<my name>\\Miniconda2\\envs\\GPIBdriver'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

**Comment by XavierTolza** [comment]
**EDIT:** I fixed it thanks to [this post](https://stackoverflow.com/questions/43288756/pytest-xdist-lookuperror-setuptools-scm-was-unable-to-detect-version)
Do the following:

1. Revert setuptools to 1.15.0 using `pip install setuptools_scm==1.15.0`
2. Install the git project: `git+git://github.com/nelsond/prologix-gpib-ethernet.git`

Worked for me ;)

**Comment by nelsond** [comment]
I removed setuptools-scm for the new release (v0.1.2) and added CI tests for Windows. I was able to install the library using pip on Windows 10 and Python 3.5 now. Hopefully this also resolves the issues @HexaDragon had on Windows 7.
